### ISSUE TITLE
Черный ободок вокруг текстуры листьев

### ISSUE THREAD

**Issue by FunLay123** [Proxwian/OxFORTPACK#2]
Здравствуйте!
При заходе в мир листья приобрели что-то типа черного ободка или текстуры. Компьютер не очень мощный, поэтому пытался удалить мод (связанный с багом, листвой) из папки модов, но не нашел ничего похожего на название мода, который что-то делает с листвой(по типу Betterleaves или всего с названием 'Better' или 'Leaves'), поискал также в текстурпаках что-то связанное с листвой, не нашел.

Проблема возникает когда:

В настройках графики майнкрафт стоит графика Fast.
Включены любые шейдеры, кроме Complementary Reimagined и Complementaryshaders(Именно те версии шейдеров что были вместе с модпаком)
Если одна или две сразу из этих причин активны, то происходит баг с листвой.
Думаю, может вы (создатель модпака), скинете мне название мода (на украшение листвы) и я попробую его удалить, ну или может еще какие-нибудь пути решения проблемы есть. Помогите пожалуйста

Скриншот: https://imgur.com/a/U4gkvgi
Характеристики пк:
ЦП - i5 7400
GPU - Amd Radeon rx 560
Оперативка - 8 гб (для игры выделено 7300мб)

**Comment by Proxwian** [comment]
Отключите текстурпак BetterTrue, либо повысьте настройки графики для листвы. На будущее лучше спрашивайте в Discord, там уже много раз обращались с подобной проблемой. Спасибо.

**Comment by FunLay123** [comment]
Спасибо огромное! На будущее про дискорд запомню

**Comment by FunLay123** [comment]
Подождите, но у меня нет текстурпака BetterTrue, да и в дискорд сервер не могу зайти, так как предложение истекло
Насчет повышения настроек графики листвы - не помогает
![264312435-63d2d90f-f7d1-46d3-8e15-cefcd9d5bd03](https://github.com/Proxwian/OxFORTPACK/assets/137938315/dc2db878-02fc-4043-9639-405f8c31d126)
![javaw_FstW06qZJd](https://github.com/Proxwian/OxFORTPACK/assets/137938315/c1fe23dc-a677-4367-a932-dc18c8c46463)
![javaw_jEB8B5rAXd](https://github.com/Proxwian/OxFORTPACK/assets/137938315/e3b146e9-1083-4150-b6b2-24dcb8590a32)
![javaw_0i6gCwWwFH](https://github.com/Proxwian/OxFORTPACK/assets/137938315/09f0843b-edbb-404e-b1e6-9d42aae68303)

**Comment by Proxwian** [comment]
StayTrue* и смотреть надо в правой колонке, а не в левой. Приглашение в Discord исправил: https://discord.com/invite/G4wjUF32Sg

**Comment by Proxwian** [comment]
![image](https://github.com/Proxwian/OxFORTPACK/assets/31781674/9a66cd4b-f3bf-4864-9326-0d3ee95187a5)
Настройки графики

**Comment by FunLay123** [comment]
> StayTrue* и смотреть надо в правой колонке, а не в левой. Приглашение в Discord исправил: https://discord.com/invite/G4wjUF32Sg

Так блэт, StayTrue у меня отрублен, поэтому он у меня и справа, а вы написали 'отключите Staytrue', значит он должен быть в 'доступных' текстурпаках, поэтому я и отправил столбец слева
Смена параметра качества листьев ни на что не влияет.
Спасибо за исправление приглашения
![browser_Kqe0cpB1Ap](https://github.com/Proxwian/OxFORTPACK/assets/137938315/0e34f0ea-cb23-49b5-9385-d8693a18f606)

**Comment by FunLay123** [comment]
А может вы мне просто скинете название мода, который добавляет пышность листве, а я его удалю, так будет легче и мне, и вам. Ежели конечно за листву отвечает мод, а не что-то еще

**Comment by Proxwian** [comment]
СЛЕВА отображаются ДОСТУПНЫЕ текстурпаки, которые НЕ активны. СПРАВА показываются ВЫБРАННЫЕ (активные) текстурпаки. Нужно, чтобы StayTrue был СЛЕВА.

За пышность листвы отвечает только этот текстурпак, и никакая из модификаций.

**Comment by FunLay123** [comment]
> СЛЕВА отображаются ДОСТУПНЫЕ текстурпаки, которые НЕ активны. СПРАВА показываются ВЫБРАННЫЕ (активные) текстурпаки. Нужно, чтобы StayTrue был СЛЕВА.
> 
> За пышность листвы отвечает только этот текстурпак, и никакая из модификаций.

Извините, честно, виноват, не понял вас сразу, спасибо за помощь,
